#!/bin/bash

package_name="graffiti"
link_clifty="https://github.com/shivamadhau/graffiti"
link_graffiti_raw="https://raw.githubusercontent.com/shivamadhau/graffiti/main"

clear
cd $HOME

version=$(curl -s "https://github.com/shivamadhau/graffiti/assets/update/version.txt")
version="1.0"

#Check whether package is installed
package_installed() {
    local package_name=$1

    if dpkg -l | awk '{print $2}' | grep -wq "$package_name"; then
        return 0  # Package is installed
    else
        return 1  # Package is not installed
    fi
}

latest_version() {
    current_ver=$(graffiti -v)
    if [ "$version" == "$current_ver" ]; then
        graffiti -cb
        echo -ne  "\nYou already have graffiti latest version"
        echo -ne "\nType 'graffiti' to run it"
    else 
        install_now
    fi
}

# Function to install dependencies
dependencies() {
    if [[ $(command -v curl) ]]; then
        echo -ne ""
    else
        pkgs=(curl wget)
        for pkg in "${pkgs[@]}"; do
            type -p "$pkg" &>/dev/null || {
                if [[ $(command -v pkg) ]]; then
                    pkg install "$pkg" -y
                elif [[ $(command -v apt) ]]; then
                    apt install "$pkg" -y
                elif [[ $(command -v apt-get) ]]; then
                    apt-get install "$pkg" -y
                elif [[ $(command -v pacman) ]]; then
                    sudo pacman -S "$pkg" --noconfirm
                elif [[ $(command -v dnf) ]]; then
                    sudo dnf -y install "$pkg"
                else
                    echo -e "\n it isnt supported to bash json, Install packages manually."
                    { reset_color; exit 1; }
                fi
            }
        done
    fi
}

# Function to set variables
variables() {
    version=$(curl -s https://raw.githubusercontent.com/shivamadhau/graffiti/main/assets/update/version.txt)
    link_clifty="https://github.com/shivamadhau/graffiti"
}

# Function to install Clifty
install_deb() {
    wget --no-check-certificate https://github.com/Alygnt/Clifty/releases/tag/v_1.5/clifty_1.5.deb > /dev/null 2>&1
    if [[ $(command -v termux-chroot) ]]; then
        termux-chroot dpkg -i clifty_${version}.deb
    else
        if [ "$SUDO_USER" ]; then
            sudo dpkg -i "clifty_${version}.deb"
        else
            dpkg -i "clifty_${version}.deb"
        fi
    fi
    rm -rf clifty_${version}.deb
}

# Function to clean up
clean() {
    if [ -e install ]; then
        rm -rf install
    fi
}

# Function to run Clifty
run() {
    if [ "$SUDO_USER" ]; then
        sudo graffiti
    else
        graffiti
    fi
}

finish(){
    clear
    graffiti -b
    echo -ne "\nGraffiti tool is now ready type 'graffiti' to run it"
}

install_now(){
    dependencies
    variables
    install_deb
}

if package_installed "$package_name"; then
    latest_version
else
    install_now
    finish
fi
